name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install Cypress
        run: npx cypress install

      - name: Set Cypress permissions
        run: chmod +x $(npm bin)/cypress

      - name: Start Flask server
        run: |
          source venv/bin/activate
          flask run --host=0.0.0.0 --port=5000 &
        env:
          FLASK_APP: app.py
          FLASK_ENV: development
        timeout-minutes: 2

      - name: Run Cypress tests
        run: npx cypress run --verbose
        env:
          CYPRESS_baseUrl: "http://127.0.0.1:5000"
