name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Configuração inicial
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Instalação de dependências
      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node.js dependencies
        run: npm ci

      # Instalação do Cypress
      - name: Install Cypress
        run: npx cypress install

      # Instalação do Chromium (necessário para o Cypress headless)
      - name: Install Chromium
        run: sudo apt-get install -y chromium-browser

      # Inicialização do servidor Flask
      - name: Start Flask server
        run: |
          source venv/bin/activate
          flask run --host=0.0.0.0 --port=5000 > flask.log 2>&1 &
        env:
          FLASK_APP: app.py
          FLASK_ENV: development
        timeout-minutes: 2

      # Aguarde até que o Flask esteja pronto para aceitar conexões
      - name: Wait for Flask server to be available
        run: |
          for i in {1..30}; do
            if curl --silent --fail http://127.0.0.1:5000/predict; then
              echo "Flask server is up!"
              break
            else
              echo "Waiting for Flask to be available..."
              sleep 1
            fi
          done

      # Executa o benchmark após a confirmação de que o Flask está rodando
      - name: Run benchmark
        run: |
          source venv/bin/activate
          python benchmark.py
        env:
          FLASK_APP: app.py

      # Upload de logs para depuração
      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: |
            flask.log
            cypress.log


