name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Configuração inicial
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Instalação de dependências
      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node.js dependencies
        run: npm ci

      # Instalação do Cypress
      - name: Install Cypress
        run: npx cypress install

      # Inicialização do servidor Flask
      - name: Start Flask server
        run: |
          source venv/bin/activate
          flask run --host=0.0.0.0 --port=5000 > flask.log 2>&1 &
        env:
          FLASK_APP: app.py
          FLASK_ENV: development
        timeout-minutes: 2

      # Aguarde o servidor iniciar
      - name: Wait for Flask server
        run: sleep 10

      # Testes com Cypress usando Electron
      - name: Run Cypress tests
        run: |
          npx cypress run --headless --browser electron > cypress.log 2>&1
        env:
          DEBUG: cypress:*
          CYPRESS_baseUrl: "http://127.0.0.1:5000"

      # Upload de logs para depuração
      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: |
            flask.log
            cypress.log


